<?php

namespace App;

use App\Collections\ClinicCollection;
use App\Doctor;
use App\Pic;
use App\Category;
use Illuminate\Database\Eloquent\Model;

class Clinic extends Model
{
    protected $fillable = [
        'name', 'address', 'phones', 'clinic_rating', 'comfort_rating', 'discipline_rating', 'rating', 'user_id',
        'title', 'description', 'keywords', 'logo', 'child', 'fullDay',
    ];

    protected $casts = [
      'phones' => 'array',
    ];

    public function newCollection(array $models = [])
    {
        return new ClinicCollection($models); // TODO: Change the autogenerated stub
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function doctors()
    {
        return $this->belongsToMany(Doctor::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
    public function services()
    {
        return $this->belongsToMany(Service::class)->withPivot([
            'service_price',
        ]);
    }

    public function likes()
    {
        return $this->morphMany(Like::class, 'likeable');
    }

    public function pics()
    {
        return $this->belongsToMany(Pic::class);
    }
    public function feedbacks()
    {
        return $this->belongsToMany(Feedback::class);
    }
    public static function getRecord(Clinic $clinic)
    {
//        return Record::all()->where('clinic_id', $clinic->id);
    }

    public static function getScheduleActivated(Clinic $clinic)
    {
        return Schedule::all()
            ->where('clinic_id', $clinic->id)
            ->where('active', true)
            ->where('accepted', false)
            ->groupBy('date_of_record');
    }
}
