<?php

namespace App;

use App\Collections\DoctorCollection;
use App\Spec;
use App\Clinic;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Symfony\Component\HttpFoundation\Request;

class Doctor extends Model
{
    protected $fillable = [
        'address', 'educations', 'experiences', 'price', 'discount', 'attent_rating', 'manner_rating', 'time_rating', 'rating' ,'user_id'
    ];

    protected $casts = [
        'educations' => 'array',
        'experiences' => 'array',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function clinic()
    {
        return $this->belongsTo(Clinic::class);
    }

    public function specs()
    {
        return $this->belongsToMany(Spec::class);
    }
    public function services()
    {
        return $this->belongsToMany(Service::class);
    }

    public function pics()
    {
        return $this->belongsToMany(Pic::class);
    }
    public function schedules()
    {
        return $this->belongsToMany(Schedule::class);
    }

    public function feedbacks()
    {
        return $this->belongsToMany(Feedback::class);
    }

    public function newCollection(array $models = [])
    {
        return new DoctorCollection($models); // TODO: Change the autogenerated stub
    }

    public static function getSchedule(Doctor $doctor)
    {
        return Schedule::all()
            ->where('doctor_id', $doctor->id)
            ->groupBy('date_of_record');
    }

    public static function getScheduleActivated(Doctor $doctor)
    {
        return Schedule::all()
            ->where('doctor_id', $doctor->id)
            ->where('active', true)
            ->where('accepted', false)
            ->groupBy('date_of_record');
    }
}
